### PR TITLE
OT-4622 Use the Fedex based the Shipment Event type

### PR DESCRIPTION
**Pull request by venkyj**
We are not correctly setting the Shipment event's type in the code. I added a map based on Fedex codes.

### CODE REVIEW

**Comment by jedprentice** [comment]
@venkyj So did you just map UPS status event codes to the event codes used by FedEx? Not that there's anything wrong with it, just trying to understand what problem you are solving and how you got to the solution.

**Comment by venkyj** [comment]
I had worked on the Endicia API updates recently. It has a similar map from Endicia Status codes to Fedex Status codes in active_shipping/lib/active_shipping/shipping/carriers/endicia.rb called ENDICIA_EVENT_CODES.

The code in OT seems to look for a specific set of codes. With this mapping, we could get a simpler interface for the OT side to look at the status of the shipment.

**Comment by jedprentice** [comment]
@venkyj Since this seems to more or less be our gem now and not a fork of active_shipping, this is probably OK. I think if we were expecting to maintain compatibility with active_shipping I'd want an API adapter in OT to do this rather than doing it here.

**Comment by venkyj** [comment]
@jedprentice I agree with the approach of using an API adapter to the active_shipping. If we decide to use the Shopify's active shipping, this code needs to go to that adapter.

**Comment by venkyj** [comment]
Jenkins, retest this please.

**Pull request merged**
