### PR TITLE
Mail innovations

### PR DESCRIPTION
**Pull request by psujohn**

### CODE REVIEW

**Comment by jedprentice** [comment]
CI failed with a missing constant error:

    /home/ubuntu/jenkins/workspace/active_shipping-pr/lib/active_shipping/shipping/response.rb:5:in `<module:Shipping>': uninitialized constant ActiveMerchant::ActiveMerchantError (NameError)

**Comment by psujohn** [comment]
jenkins, retest this please

**Comment by psujohn** [comment]
Not sure why but this doesn't pass on CI but does run locally. Pretty sure that's the current state of our active shipping fork and will be until we get the merge upstream stuff done.

**Comment by psujohn** [comment]
@jedprentice I don't think it's worth fussing with CI until we get the merge upstream in. Can you look this over and if it looks okay we'll merge.

**Comment by jedprentice** [comment]
@psujohn Looks good to me. Bummer about CI.

**Pull request merged**
