### PR TITLE
OT-4514 OT-4515 OT-4516 OT-4517 update endicia api

### PR DESCRIPTION
**Pull request by venkyj**
Individual tickets tied to OT-4436

### CODE REVIEW

**Comment by jedprentice** [comment]
@venkyj CI failed:

    uninitialized constant ActiveMerchant::ActiveMerchantError

I know failures are par for the course in this repo; is this typical?

**Comment by jedprentice** [comment]
@venkyj Looks fine to me... @psujohn can you have a look?

**Comment by venkyj** [comment]
Thanks @jedprentice. I will take a look at the cause of the CI failure (though it has succeeded after the merge).

**Comment by venkyj** [comment]
Updated the version of active_utils to 2.2.3 (same version as OT)

**Comment by venkyj** [comment]
Jenkins, retest this please.

**Pull request merged**
